#!/usr/bin/env bash

if [ $(find . -name '*.go' | wc -l) -eq 0 ]; then
	echo "It does not seem to have a Go project in the current directory"
	exit 1
fi

dbg_args=""
if [ $# -gt 0 ]; then
	dbg_args="-- $@"
fi

exec dlv debug --headless --listen=:2345 --log ${dbg_args}
