FROM juli3nk/dev

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
	&& set -x \
	&& curl -sL https://deb.nodesource.com/setup_10.x | bash - \
	&& apt-get install -y --no-install-recommends \
		nodejs \
	&& apt-get -y autoremove \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
