FROM debian:stable-slim AS builder

ARG GO_VERSION=1.19.2
ARG PROTOBUF_VERSION=3.19.1
ARG GRPCWEB_VERSION=1.2.1
ARG BUF_VERSION=0.56.0

RUN set -x \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		unzip

RUN set -x \
	# Install Go
	&& curl -sfL https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz | tar -xzC /tmp \
	# Install Protobuf
	&& curl -sfL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip > /usr/local/src/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip \
	&& unzip -d /tmp/protobuf /usr/local/src/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip \
	# Install GRPC Web
	&& curl -sfL https://github.com/grpc/grpc-web/releases/download/${GRPCWEB_VERSION}/protoc-gen-grpc-web-${GRPCWEB_VERSION}-linux-x86_64 -o /tmp/protoc-gen-grpc-web \
	&& chmod +x /tmp/protoc-gen-grpc-web \
	# Install Buf
	&& curl -sfL https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-Linux-x86_64 -o /tmp/buf \
	&& curl -sfL https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/protoc-gen-buf-check-breaking-Linux-x86_64 -o /tmp/protoc-gen-buf-check-breaking \
	&& curl -sfL https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/protoc-gen-buf-check-lint-Linux-x86_64 -o /tmp/protoc-gen-buf-check-lint \
	&& chmod +x /tmp/buf /tmp/protoc-gen-buf-*


FROM juli3nk/dev

ENV GOPATH=/go \
	GOARCH=amd64 \
	PATH=/go/bin:/usr/local/go/bin:$PATH

COPY data/profile/go.sh /etc/profile.d/go.sh

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections \
	&& set -x \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends \
		gccgo \
	&& apt-get -y autoremove \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=builder /tmp/go /usr/local/go
COPY --from=builder /tmp/protobuf/bin/protoc /usr/local/bin/
COPY --from=builder /tmp/protobuf/include/google /usr/local/include/google
COPY --from=builder /tmp/protoc-gen-grpc-web /usr/local/bin/
COPY --from=builder /tmp/buf /usr/local/bin/
COPY --from=builder /tmp/protoc-gen-buf-* /usr/local/bin/

RUN set -x \
	# Install gRPC
	#&& go get -u google.golang.org/grpc \
	# Install protoc-gen-go
	#&& GO111MODULE=off go get -d -u google.golang.org/protobuf/cmd/protoc-gen-go \
	#&& git -C "$(go env GOPATH)"/src/google.golang.org/protobuf checkout v${PROTOBUF_GO_VERSION} \
	#&& GO111MODULE=off go install google.golang.org/protobuf/cmd/protoc-gen-go \
	&& GO111MODULE=off go get google.golang.org/protobuf/cmd/protoc-gen-go \
	# Install protoc-gen-go-grpc
	&& GO111MODULE=off go get google.golang.org/grpc/cmd/protoc-gen-go-grpc \
	# Install protoc-gen-gotagger
	&& GO111MODULE=off go get github.com/juli3nk/protoc-gen-gotagger \
	&& GO111MODULE=off go get honnef.co/go/tools/cmd/staticcheck

WORKDIR /go/src
